### ISSUE TITLE
exe problem

### ISSUE THREAD

**Issue by 12bucklemyshoe111** [Hawkishx/Thief-Cat#3]
when I make it into an exe it never gives me the file it just like gives me the crashing blue circle then after like 10 secs nothing happends

**Comment by Hawkishx** [comment]
do not enable "hide" to see

**Comment by 12bucklemyshoe111** [comment]
Do they still need python and the requirments or no

**Comment by 12bucklemyshoe111** [comment]
also I dont really know what u mean I turned on hidden file thing but still dont see it
